# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/otus_cpp_p_DZ_4/otus_cpp_p_DZ_4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/otus_cpp_p_DZ_4/otus_cpp_p_DZ_4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/bin/cpack --config ./CPackSourceConfig.cmake /home/runner/work/otus_cpp_p_DZ_4/otus_cpp_p_DZ_4/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/otus_cpp_p_DZ_4/otus_cpp_p_DZ_4/CMakeFiles /home/runner/work/otus_cpp_p_DZ_4/otus_cpp_p_DZ_4//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/otus_cpp_p_DZ_4/otus_cpp_p_DZ_4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named graphicseditordecl

# Build rule for target.
graphicseditordecl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graphicseditordecl
.PHONY : graphicseditordecl

# fast build rule for target.
graphicseditordecl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/build
.PHONY : graphicseditordecl/fast

editor.o: editor.cpp.o
.PHONY : editor.o

# target to build an object file
editor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/editor.cpp.o
.PHONY : editor.cpp.o

editor.i: editor.cpp.i
.PHONY : editor.i

# target to preprocess a source file
editor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/editor.cpp.i
.PHONY : editor.cpp.i

editor.s: editor.cpp.s
.PHONY : editor.s

# target to generate assembly for a file
editor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/editor.cpp.s
.PHONY : editor.cpp.s

ellipse.o: ellipse.cpp.o
.PHONY : ellipse.o

# target to build an object file
ellipse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/ellipse.cpp.o
.PHONY : ellipse.cpp.o

ellipse.i: ellipse.cpp.i
.PHONY : ellipse.i

# target to preprocess a source file
ellipse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/ellipse.cpp.i
.PHONY : ellipse.cpp.i

ellipse.s: ellipse.cpp.s
.PHONY : ellipse.s

# target to generate assembly for a file
ellipse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/ellipse.cpp.s
.PHONY : ellipse.cpp.s

graphicsitem.o: graphicsitem.cpp.o
.PHONY : graphicsitem.o

# target to build an object file
graphicsitem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/graphicsitem.cpp.o
.PHONY : graphicsitem.cpp.o

graphicsitem.i: graphicsitem.cpp.i
.PHONY : graphicsitem.i

# target to preprocess a source file
graphicsitem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/graphicsitem.cpp.i
.PHONY : graphicsitem.cpp.i

graphicsitem.s: graphicsitem.cpp.s
.PHONY : graphicsitem.s

# target to generate assembly for a file
graphicsitem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/graphicsitem.cpp.s
.PHONY : graphicsitem.cpp.s

gui.o: gui.cpp.o
.PHONY : gui.o

# target to build an object file
gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/gui.cpp.o
.PHONY : gui.cpp.o

gui.i: gui.cpp.i
.PHONY : gui.i

# target to preprocess a source file
gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/gui.cpp.i
.PHONY : gui.cpp.i

gui.s: gui.cpp.s
.PHONY : gui.s

# target to generate assembly for a file
gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/gui.cpp.s
.PHONY : gui.cpp.s

line.o: line.cpp.o
.PHONY : line.o

# target to build an object file
line.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/line.cpp.o
.PHONY : line.cpp.o

line.i: line.cpp.i
.PHONY : line.i

# target to preprocess a source file
line.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/line.cpp.i
.PHONY : line.cpp.i

line.s: line.cpp.s
.PHONY : line.s

# target to generate assembly for a file
line.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/line.cpp.s
.PHONY : line.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicseditordecl.dir/build.make CMakeFiles/graphicseditordecl.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... graphicseditordecl"
	@echo "... editor.o"
	@echo "... editor.i"
	@echo "... editor.s"
	@echo "... ellipse.o"
	@echo "... ellipse.i"
	@echo "... ellipse.s"
	@echo "... graphicsitem.o"
	@echo "... graphicsitem.i"
	@echo "... graphicsitem.s"
	@echo "... gui.o"
	@echo "... gui.i"
	@echo "... gui.s"
	@echo "... line.o"
	@echo "... line.i"
	@echo "... line.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

